"""Build the self-contained Revival landing page from verified Ministries content."""
from pathlib import Path
import json,html
root=Path(__file__).resolve().parents[1]/'docs'
data=json.loads((root/'content/ministries.json').read_text())
def e(s):return html.escape(s,quote=True)
def apply(label='Start My Revival Application',small=False):
 return '<button type="button" data-apply class="cta'+(' small' if small else '')+'">'+label+'<span aria-hidden="true">↗</span></button>'
challenges=''.join(f'<article class="challenge"><span class="number">0{i}</span><div><h3>{e(c["title"])}</h3><p>{e(c["body"])}</p></div></article>' for i,c in enumerate(data['challenges'],1))
pillars=''.join(f'<div class="pillar"><img src="images/pillar-{n.lower()}.png" alt="" width="128" height="128" loading="lazy"><h3>{n}</h3></div>' for n in ['Faith','Family','Fitness','Finances'])
testimonials=''.join(f'<figure class="testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>{e(t["quote"])}</blockquote><figcaption><strong>{e(t["name"])}</strong><span>{e(t["church"])}</span></figcaption></figure>' for t in data['testimonials'])
google_reviews=''.join(f'<figure class="testimonial google-review" id="{e(t["id"])}"><div class="google-review-meta"><span>Google review</span><span class="review-stars" aria-label="{t["rating"]} out of 5 stars">★★★★★</span></div><blockquote>“{e(t["quote"])}”</blockquote><figcaption><strong>{e(t["name"])}</strong><span>{e(t["role"])}</span><a href="{e(t["url"])}" target="_blank" rel="noopener">Read full review on Google ↗</a></figcaption></figure>' for t in data.get('google_reviews',[]))
faq=[
 ('What denomination is RUK Ministries affiliated with?','RUK Ministries is a non-denominational Christian organization. We welcome pastors and spiritual leaders from all biblical-based faiths. Our teachings and programs are based on biblical principles with Jesus Christ at the core.'),
 ('What happens after the event?','After the event, you will have the opportunity to join the RUK Ministries community, a brotherhood of Christian leaders committed to supporting each other in their journey of faith and leadership. We offer ongoing training, seminars, and webinars to support your continued growth.'),
 ('What is the event designed to help me work on?','The event focuses on pastoral duties, personal life, and spiritual growth, with strategies around leadership, finance, and personal development. It aims to reignite your passion for your calling and equip you with tools to live a balanced and fulfilling life.'),
 ('What is included in the experience?','Lunch and dinner for all three days, along with additional gear provided at the event. Accommodation is separate. The team can talk through the practical details with you during the application process.'),
 ('How long is Revival?','Revival is a three-day, in-person intensive for male pastors and ministry leaders.'),
 ('What happens when I click Apply?','Start with your name, email, and phone number. Then continue to the application to tell the RUK Ministries team about your ministry and what you want to work on.')]
faqs=''.join(f'<details><summary>{e(q)}<span aria-hidden="true">+</span></summary><p>{e(a)}</p></details>' for q,a in faq)
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revival | The Man Behind the Ministry | RUK Ministries</title><meta name="description" content="A three-day, Christ-centered intensive for male pastors and ministry leaders. Faith, Family, Fitness, and Finances."><meta name="robots" content="noindex,nofollow"><link rel="icon" href="images/ruk-logo.webp"><link rel="stylesheet" href="landing.css"><script src="funnel-config.js" defer></script><script src="funnel-core.js" defer></script><script src="funnel.js" defer></script></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="#main"><img src="images/ruk-logo.webp" alt="RUK Ministries" width="64" height="64"><span>REVIVAL</span></a><nav aria-label="Main navigation"><a href="#approach">Our approach</a><a href="#stories">Pastor stories</a><a href="#questions">Questions</a></nav>'''+apply('Apply for Revival',True)+'''</header>
<main id="main"><section class="hero"><div class="hero-background"></div><div class="wrap hero-grid"><div class="hero-heading"><p class="eyebrow">THREE DAYS FOR MALE PASTORS &amp; MINISTRY LEADERS</p><h1>The church gets<br>your best.<br><em>What’s left for you?</em></h1><p class="hero-copy">Everyone knows where to find you when something goes wrong. Your own struggles can stay out of the conversation. Revival gives the man behind the pulpit three days to confront what ministry has pushed aside.</p></div><div class="hero-video"><p class="video-label"><span aria-hidden="true">▶</span> THE RISE UP KINGS REVIVAL <span>1:25 · SOUND ON</span></p><div class="video-frame"><iframe src="https://fast.wistia.net/embed/iframe/5w5ll9rwvc?videoFoam=true&amp;autoPlay=false" title="The Rise Up Kings Revival introduction" allow="fullscreen; picture-in-picture" allowfullscreen></iframe></div><p class="video-caption">See the experience. Hear the purpose behind Revival.</p></div><div class="hero-action">'''+apply()+'''<p class="micro">Your details first. Then tell us what brought you here.</p></div><div class="hero-facts"><div><strong>3 DAYS</strong><span>In person. Christ-centered.</span></div><div><strong>FOR PASTORS</strong><span>The man behind the ministry.</span></div><div><strong>4 PILLARS</strong><span>Faith. Family. Fitness. Finances.</span></div></div></div></section>
<section class="section cream reality"><div class="wrap two-col"><div><p class="eyebrow">THE PASTOR BEHIND THE PULPIT</p><h2>You can’t lead<br>a church while<br><em>running on empty.</em></h2></div><div class="body-copy"><p>The sermon still needs preparing. The phone keeps ringing. Someone always needs your attention.</p><p>But at home, your mind is still in the meeting. Your Bible is open, and you’re already thinking about what somebody else needs to hear. There are things you need to say out loud, but your title makes honesty feel complicated.</p><p class="heavy">The public ministry can keep performing long after the private man starts paying for it.</p><p>Give that man attention before exhaustion, distance at home, or the thought of walking away forces the conversation.</p></div></div></section>
<section class="section approach" id="approach"><div class="wrap"><div class="two-col"><div><p class="eyebrow">OUR APPROACH</p><h2>Unmasking the struggles of <em>spiritual leadership.</em></h2></div><div class="body-copy"><p>'''+e(data['approach'])+'''</p><blockquote class="scripture">“For the Spirit God gave us does not make us timid, but gives us power, love, and self-discipline.”<cite>2 Timothy 1:7</cite></blockquote>'''+apply('Apply for Revival')+'''</div></div><figure class="training"><img src="images/revival-training-full.png" alt="The full RUK training room, with a coach speaking to the seated group" width="3891" height="1984" loading="lazy"><figcaption>RUK MINISTRIES <span>FAITH · FAMILY · FITNESS · FINANCES</span></figcaption></figure></div></section>
<section class="section cream why" id="why"><div class="wrap two-col"><div class="section-intro"><p class="eyebrow">WHY RISE UP KINGS</p><h2>Empowering pastors to overcome <em>unique challenges.</em></h2><p class="subheading">And thrive in their calling.</p><p>'''+e(data['why_intro'])+'''</p></div><div class="challenge-list">'''+challenges+'''</div></div></section>
<section class="section pillars"><div class="wrap"><p class="eyebrow">FAITH. FAMILY. FITNESS. FINANCES.</p><h2>RUK 4 Pillars <em>of Power.</em></h2><div class="pillar-grid">'''+pillars+'''</div></div></section>
<section class="section cream stories" id="stories"><div class="wrap"><div class="section-heading"><p class="eyebrow">IN THEIR OWN WORDS</p><h2>Real stories. <em>Real impact.</em></h2><p>Google reviews and pastor accounts.</p></div><div class="google-reviews" id="google-reviews"><h3 class="review-group-title">Google reviews mentioning Revival</h3><div class="testimonial-grid">'''+google_reviews+'''</div></div><h3 class="review-group-title">Pastor accounts from RUK Ministries</h3><div class="testimonial-grid">'''+testimonials+'''</div><div class="center-cta">'''+apply('Apply for Revival')+'''</div></div></section>
<section class="section ministry"><div class="wrap two-col"><div><p class="eyebrow">RUK MINISTRIES</p><h2>For the life behind <em>the calling.</em></h2><p>We help men step into their God-given potential and gain power and self-discipline.</p><ul class="question-list"><li>Do you struggle showing up powerfully every day?</li><li>Have you lost your fire and passion?</li><li>Do you find it difficult to stay balanced serving your congregation while staying connected to your wife and kids?</li><li>Have you lost the passion in your marriage?</li><li>Do you believe God has called you to do more?</li><li>Have you considered leaving ministry altogether?</li></ul>'''+apply('Start Your Revival Application')+'''</div><div class="rooted"><p class="eyebrow">OUR FOUNDATION</p><h2>Rooted in the Word<br>of <em>Christ Jesus.</em></h2>'''+''.join('<p>'+e(x)+'</p>' for x in data['rooted'])+'''<a href="https://rukministries.com/faith-statement" target="_blank" rel="noopener">Read our statement of faith ↗</a></div></div></section>
<section class="section cream faq" id="questions"><div class="wrap two-col"><div><p class="eyebrow">FAQ</p><h2>Got questions?<br><em>We have answers.</em></h2></div><div>'''+faqs+'''</div></div></section>
<section class="section final-cta" id="apply"><div class="wrap"><p class="eyebrow">FOR THE MAN BEHIND THE MINISTRY</p><h2>You’ve made time<br>for everyone else.<br><em>Make time for this.</em></h2><p>Three days. Four pillars. An honest look at the life behind the calling.</p>'''+apply()+'''<p class="micro">Start with your details. Continue to the application.</p></div></section></main>
<footer class="site-footer"><div class="wrap"><a class="brand" href="#main"><img src="images/ruk-logo.webp" alt="RUK Ministries" width="60" height="60"><span>REVIVAL</span></a><p>© 2026 RUK Ministries</p>'''+apply('Apply for Revival',True)+'''</div></footer>
<dialog id="lead-modal" aria-labelledby="lead-title" aria-describedby="lead-subtitle"><button type="button" class="modal-close" aria-label="Close opt-in form">×</button><div class="modal-body"><p class="eyebrow">REVIVAL / YOUR NEXT STEP</p><h2 id="lead-title">Start your<br><em>Revival application.</em></h2><p id="lead-subtitle">Enter your details, then continue to tell us about your ministry.</p><p id="preview-notice" class="preview-notice">Approval preview. Details entered here are not sent or saved.</p><form id="lead-form" novalidate><label for="lead-name">Full name</label><input id="lead-name" type="text" name="name" autocomplete="name" maxlength="120" required><label for="lead-email">Email address</label><input id="lead-email" type="email" name="email" autocomplete="email" maxlength="254" required><label for="lead-phone">Phone number</label><input id="lead-phone" type="tel" name="phone" autocomplete="tel" maxlength="30" required><p class="consent">By continuing, you agree to receive event updates and marketing messages from Rise Up Kings. Unsubscribe at any time.</p><p id="lead-error" class="form-error" role="alert" hidden></p><button type="submit" class="cta">Continue to Application <span aria-hidden="true">→</span></button></form><p class="micro">Step 1 of 2 · Your details</p></div></dialog><noscript><p class="no-script">Please enable JavaScript to open the application form.</p></noscript></body></html>'''
(root/'index.html').write_text(page)
print('Built landing page with hero video, full training image, Ministries sections, pastor stories and opt-in modal.')
